In [167]:
import numpy as np
from numpy.linalg import norm
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import csv
from sklearn.utils import Bunch
from scipy import spatial
from sklearn.metrics import classification_report


In [168]:
def load_my_fancy_dataset():
    with open(r'data/Final_Augmented_dataset_Diseases_and_Symptoms.csv') as csv_file:
        data_reader = csv.reader(csv_file)
        feature_names = next(data_reader)[:-1]
        data = []
        target = []
        for row in data_reader:
            features = row[1:]
            label = row[0]
            data.append([float(num) for num in features])
            target.append(int(label))
        
        data = np.array(data)
        target = np.array(target)
    return Bunch(data=data, target=target, feature_names=feature_names)


In [182]:
dataset = load_my_fancy_dataset()
X = dataset.data
y = dataset.target
print(X)
print(y)
unique = set(y)
print(len(unique))

[[1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[  0   0   0 ... 772 772 772]
773


In [184]:
# Split the data into a training set and a test set
# Note: this is where we are dropping diseases on accident
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=40)

In [171]:
# Standardize the features (mean=0, variance=1) using a vectorized operation
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [172]:
# Train a classifier
clf = LogisticRegression(random_state=60, max_iter=500)
#clf = GaussianNB(var_smoothing=0.25)
clf.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=500, random_state=60)

In [173]:
# user input from csv -> array
user_input = [0] * 377
with open(r'data/User_Input.csv') as csv_file:
    data_reader = csv.reader(csv_file)
    data = next(data_reader)
    print(data)
for item in range(len(data)):
    data[item] = int(data[item])
    user_input[data[item]] = 1
print(user_input)

['165', '118', '192', '208', '168', '3', '4', '5', '6', '7', '13', '32', '55']
[0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [179]:
# Predict the test set results
y_pred = clf.predict(X_test_scaled)
user_input = np.array(user_input)
user_input = user_input.reshape(1, -1)
#clf.fit(user_input,)
user_pred = clf.predict(user_input)
print("User Prediction: ", user_pred)
# Output the accuracy of the classifier
print('Accuracy: {:.2f}'.format(accuracy_score(y_test, y_pred)))
#print(y_pred)
#print(y_test)
#print(classification_report(y_test, y_pred, zero_division=True))
print("]nClassifier performance on traingin dataset\n")
print(classification_report(y_train,clf.predict(X_train), zero_division=True))
print("\nClassifier performance on test dataset\n")
print(classification_report(y_test, y_pred, zero_division=True))
print("\nConfidence measure:")
probabilities = clf.predict_proba(user_input)
predicted_class = 'Class-' + str(np.argmax(probabilities))
#print('\nDatapoint:', user_input)
#print('Predicted class:', predicted_class)
print(probabilities)
prob2 = [probabilities]
highest_3 = [prob2[0][0][0], 0, 0]
highest_3_i = [0, 0, 0]
for i in range(len(prob2[0][0])):
    if prob2[0][0][i] > highest_3[0]:
        highest_3[0] = prob2[0][0][i]
        highest_3_i[0] = i+5
        continue
    elif prob2[0][0][i] > highest_3[1]:
        highest_3[1] = prob2[0][0][i]
        highest_3_i[1] = i+5
        continue
    elif prob2[0][0][i] > highest_3[2]:
        highest_3[2] = prob2[0][0][i]
        highest_3_i[2] = i+5
        continue
print(highest_3)
print(highest_3_i)
print(len(prob2[0][0]))
print(max(prob2[0][0]))
#for i in probabilities:


User Prediction:  [729]
Accuracy: 0.86
]nClassifier performance on traingin dataset

              precision    recall  f1-score   support

           0       0.95      0.92      0.94       723
           1       1.00      0.78      0.88        77
           3       1.00      1.00      1.00         4
           4       0.53      1.00      0.70        23
           5       0.95      0.84      0.90       263
           6       0.86      0.77      0.81        88
           7       1.00      0.98      0.99       109
           8       0.99      0.95      0.97       372
           9       0.89      0.91      0.90       139
          10       1.00      0.07      0.13        14
          11       0.64      0.90      0.75        51
          12       0.93      0.90      0.91        88
          13       0.68      0.93      0.79        44
          14       1.00      0.93      0.96        27
          15       0.95      0.85      0.89       741
          16       0.64      0.64      0.64       